version: '2'
services:
    cigna-app:
        image: cigna
        external_links:
            - cigna-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cigna?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8008:8008
    cigna-mysql:
        extends:
            file: mysql.yml
            service: cigna-mysql
